# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
  labels:
    app: mariadb-headless
spec:
  ports:
  - name: mariadb
    port: 3306
  clusterIP: None
  selector:
    app: mariadb-headless
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    app: mariadb

